---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/auth/login":
    post:
      summary: User login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/auth/logout":
    get:
      summary: User logout
      tags:
      - Authentication
      security:
      - bearerAuth: []
      responses:
        '200':
          description: User logged out successfully
  "/todos/{todo_id}/items":
    parameters:
    - name: todo_id
      in: path
      description: Todo ID
      required: true
      schema:
        type: integer
    post:
      summary: Create a new todo item
      tags:
      - Todo Items
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: item created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
              required:
              - title
  "/todos/{todo_id}/items/{iid}":
    parameters:
    - name: todo_id
      in: path
      description: Todo ID
      required: true
      schema:
        type: integer
    - name: iid
      in: path
      description: Todo Item ID
      required: true
      schema:
        type: integer
    get:
      summary: Retrieve a specific todo item
      tags:
      - Todo Items
      security:
      - bearerAuth: []
      responses:
        '200':
          description: item found
        '404':
          description: item not found
    put:
      summary: Update a specific todo item
      tags:
      - Todo Items
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: item updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
              required:
              - title
              - completed
    delete:
      summary: Delete a specific todo item
      tags:
      - Todo Items
      security:
      - bearerAuth: []
      responses:
        '204':
          description: item deleted
        '404':
          description: item not found
  "/todos":
    get:
      summary: List all todos with their items
      tags:
      - Todos
      security:
      - bearerAuth: []
      responses:
        '200':
          description: todos retrieved
    post:
      summary: Create a new todo
      tags:
      - Todos
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: todo created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
  "/todos/{id}":
    parameters:
    - name: id
      in: path
      description: Todo ID
      required: true
      schema:
        type: integer
    get:
      summary: Get a todo
      tags:
      - Todos
      security:
      - bearerAuth: []
      responses:
        '200':
          description: todo found
        '404':
          description: todo not found
    put:
      summary: Update a todo
      tags:
      - Todos
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: todo updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
    delete:
      summary: Delete a todo and its items
      tags:
      - Todos
      security:
      - bearerAuth: []
      responses:
        '204':
          description: todo deleted
        '404':
          description: todo not found
  "/signup":
    post:
      summary: Signup a new user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: User created successfully
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
